### PR TITLE
fix(SlashCommandBuilder): allow subcommands and groups to coexist at the root level

### LINKED ISSUE #25: Can't mix subcommands and subcommand groups at the root level
If we try to mix subcommands and subcommand groups at the root level of a SlashCommandBuilder, we get the following error when the call to `.addSubcommand()` happens : `RangeError: You cannot mix subcommands and subcommand groups at the root level.`
Example :
```js
new SlashCommandBuilder().setName("demo").setDescription("demo of the issue")
    .addSubcommandGroup(option => option.setName("group").setDescription("group").addSubcommand(option => option.setName("subcommand_in_group").setDescription("Subcommand in a group")))
    .addSubcommand(option => option.setName("root_subcommand").setDescription("Subcommand at the root"))
 ```
But nothing in the Discord API seems to prevent this. Actually, if we submit the command as JSON written by hand to the API or if we just comment the line that perform this check in the `.addSubcommand()` method, it works juste fine and the command can be successfully registered.
The obvious solution is to remove the check for this from the method.

### PR DESCRIPTION
**Pull request by Khasms**
**Please describe the changes this PR makes and why it should be merged:**
As shown in #25 and as confirmed to me in DAPI, the root level of slash commands supports having both subcommands and subcommand groups, but builders does not. This PR removes the checks that prevented this and updates the relevant types. Also, the new return type name is quite lengthy so I'm open to suggestions on a more concise name.

fix #25 

**Status and versioning classification:**
- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating

### CODE REVIEW

File: src/interactions/slashCommands/SlashCommandBuilder.ts [hunk 1]
```diff
@@ -44,16 +44,12 @@ export class SlashCommandBuilder {
 		input:
 			| SlashCommandSubcommandGroupBuilder
 			| ((subcommandGroup: SlashCommandSubcommandGroupBuilder) => SlashCommandSubcommandGroupBuilder),
-	): SlashCommandSubcommandGroupsOnlyBuilder {
+	): SlashCommandSubcommandsAndSubcommandGroupsOnlyBuilder {
```
Comment (vladfrangu) [inline src/interactions/slashCommands/SlashCommandBuilder.ts:47]: `SlashCommandsBuilderWithoutOptions` maybe? @discordjs/the-big-3

**Review by vladfrangu — CHANGES_REQUESTED** [review]

File: src/interactions/slashCommands/SlashCommandBuilder.ts (hunk 1 above)
Comment (kyranet) [reply src/interactions/slashCommands/SlashCommandBuilder.ts:47]: `SlashCommandsBuilder` and `SlashCommandsBuilderWithOptions` maybe?

Comment (vladfrangu) [reply src/interactions/slashCommands/SlashCommandBuilder.ts:47]: Former is the general, non strict type. Can't use it for this..

Comment (kyranet) [reply src/interactions/slashCommands/SlashCommandBuilder.ts:47]: Then yes, `SlashCommandsBuilderWithoutOptions` sounds good

Comment (Khasms) [reply src/interactions/slashCommands/SlashCommandBuilder.ts:47]: Are subcommands not technically options as well?

Comment (vladfrangu) [reply src/interactions/slashCommands/SlashCommandBuilder.ts:47]: `SlashCommandsSubcommandsOnly` will be enough for now.. Since there will be a rename later

**Review by vladfrangu — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Review by iCrawl — APPROVED** [review]
